import mongoose from "mongoose";
import { Food } from "../lib/models/Food";

const MONGODB_URI = process.env.MONGODB_URI || "mongodb://localhost:27017/dietapp";

const sampleFoods = [
  {
    source: "usda" as const,
    externalId: "usda-chicken-breast",
    name: "Chicken Breast",
    brand: "Generic",
    description: "Grilled chicken breast, skinless",
    category: "Protein",
    servingSize: 100,
    servingUnit: "g",
    servingDescription: "3.5 oz (100g)",
    isPublic: true,
    isVerified: true,
    nutrition: {
      calories: 165,
      proteinG: 31,
      carbsG: 0,
      fatG: 3.6,
      sodiumMg: 74,
    },
    searchKeywords: ["chicken", "breast", "grilled", "protein", "lean"],
  },
  {
    source: "usda" as const,
    externalId: "usda-brown-rice",
    name: "Brown Rice",
    brand: "Generic",
    description: "Cooked brown rice",
    category: "Grains",
    servingSize: 195,
    servingUnit: "g",
    servingDescription: "1 cup cooked (195g)",
    isPublic: true,
    isVerified: true,
    nutrition: {
      calories: 216,
      proteinG: 5,
      carbsG: 45,
      fatG: 1.8,
      fiberG: 3.5,
      sodiumMg: 10,
    },
    searchKeywords: ["rice", "brown", "grain", "carbs", "whole grain"],
  },
  {
    source: "usda" as const,
    externalId: "usda-banana",
    name: "Banana",
    brand: "Generic",
    description: "Medium banana, raw",
    category: "Fruit",
    servingSize: 118,
    servingUnit: "g",
    servingDescription: "1 medium (118g)",
    isPublic: true,
    isVerified: true,
    nutrition: {
      calories: 105,
      proteinG: 1.3,
      carbsG: 27,
      fatG: 0.4,
      fiberG: 3.1,
      sugarG: 14,
      potassiumMg: 422,
    },
    searchKeywords: ["banana", "fruit", "potassium"],
  },
  {
    source: "usda" as const,
    externalId: "usda-egg",
    name: "Egg",
    brand: "Generic",
    description: "Large egg, whole, cooked",
    category: "Protein",
    servingSize: 50,
    servingUnit: "g",
    servingDescription: "1 large (50g)",
    isPublic: true,
    isVerified: true,
    nutrition: {
      calories: 78,
      proteinG: 6,
      carbsG: 0.6,
      fatG: 5,
      cholesterolMg: 186,
      sodiumMg: 62,
    },
    searchKeywords: ["egg", "eggs", "protein", "breakfast"],
  },
  {
    source: "usda" as const,
    externalId: "usda-greek-yogurt",
    name: "Greek Yogurt",
    brand: "Generic",
    description: "Plain Greek yogurt, nonfat",
    category: "Dairy",
    servingSize: 170,
    servingUnit: "g",
    servingDescription: "1 container (170g)",
    isPublic: true,
    isVerified: true,
    nutrition: {
      calories: 100,
      proteinG: 17,
      carbsG: 6,
      fatG: 0.7,
      sugarG: 4,
      calciumMg: 187,
    },
    searchKeywords: ["yogurt", "greek", "dairy", "protein", "breakfast"],
  },
  {
    source: "usda" as const,
    externalId: "usda-oatmeal",
    name: "Oatmeal",
    brand: "Generic",
    description: "Oatmeal, cooked with water",
    category: "Grains",
    servingSize: 234,
    servingUnit: "g",
    servingDescription: "1 cup cooked (234g)",
    isPublic: true,
    isVerified: true,
    nutrition: {
      calories: 158,
      proteinG: 6,
      carbsG: 27,
      fatG: 3.2,
      fiberG: 4,
      sodiumMg: 115,
    },
    searchKeywords: ["oatmeal", "oats", "breakfast", "grain", "fiber"],
  },
  {
    source: "usda" as const,
    externalId: "usda-salmon",
    name: "Salmon",
    brand: "Generic",
    description: "Atlantic salmon, cooked",
    category: "Protein",
    servingSize: 100,
    servingUnit: "g",
    servingDescription: "3.5 oz (100g)",
    isPublic: true,
    isVerified: true,
    nutrition: {
      calories: 208,
      proteinG: 20,
      carbsG: 0,
      fatG: 13,
      saturatedFatG: 3.1,
      sodiumMg: 59,
    },
    searchKeywords: ["salmon", "fish", "omega-3", "protein", "seafood"],
  },
  {
    source: "usda" as const,
    externalId: "usda-broccoli",
    name: "Broccoli",
    brand: "Generic",
    description: "Broccoli, steamed",
    category: "Vegetable",
    servingSize: 156,
    servingUnit: "g",
    servingDescription: "1 cup chopped (156g)",
    isPublic: true,
    isVerified: true,
    nutrition: {
      calories: 55,
      proteinG: 3.7,
      carbsG: 11,
      fatG: 0.6,
      fiberG: 5.1,
      vitaminCMg: 101,
    },
    searchKeywords: ["broccoli", "vegetable", "green", "fiber", "vitamin c"],
  },
  {
    source: "usda" as const,
    externalId: "usda-almonds",
    name: "Almonds",
    brand: "Generic",
    description: "Almonds, raw",
    category: "Nuts",
    servingSize: 28,
    servingUnit: "g",
    servingDescription: "1 oz (28g, ~23 almonds)",
    isPublic: true,
    isVerified: true,
    nutrition: {
      calories: 164,
      proteinG: 6,
      carbsG: 6,
      fatG: 14,
      fiberG: 3.5,
      vitaminEMg: 7.3,
    },
    searchKeywords: ["almonds", "nuts", "snack", "healthy fat"],
  },
  {
    source: "usda" as const,
    externalId: "usda-avocado",
    name: "Avocado",
    brand: "Generic",
    description: "Avocado, raw",
    category: "Fruit",
    servingSize: 150,
    servingUnit: "g",
    servingDescription: "1 medium (150g)",
    isPublic: true,
    isVerified: true,
    nutrition: {
      calories: 240,
      proteinG: 3,
      carbsG: 13,
      fatG: 22,
      fiberG: 10,
      potassiumMg: 727,
    },
    searchKeywords: ["avocado", "healthy fat", "fruit", "guacamole"],
  },
  {
    source: "usda" as const,
    externalId: "usda-sweet-potato",
    name: "Sweet Potato",
    brand: "Generic",
    description: "Sweet potato, baked",
    category: "Vegetable",
    servingSize: 200,
    servingUnit: "g",
    servingDescription: "1 medium (200g)",
    isPublic: true,
    isVerified: true,
    nutrition: {
      calories: 180,
      proteinG: 4,
      carbsG: 41,
      fatG: 0.2,
      fiberG: 6.6,
      vitaminAIu: 38433,
    },
    searchKeywords: ["sweet potato", "vegetable", "carbs", "vitamin a"],
  },
  {
    source: "usda" as const,
    externalId: "usda-coffee",
    name: "Coffee",
    brand: "Generic",
    description: "Coffee, brewed, black",
    category: "Beverage",
    servingSize: 240,
    servingUnit: "ml",
    servingDescription: "1 cup (240ml)",
    isPublic: true,
    isVerified: true,
    nutrition: {
      calories: 2,
      proteinG: 0.3,
      carbsG: 0,
      fatG: 0,
      caffeineMg: 95,
    },
    searchKeywords: ["coffee", "caffeine", "beverage", "drink"],
  },
];

async function seed() {
  try {
    await mongoose.connect(MONGODB_URI);
    console.log("Connected to MongoDB");

    // Upsert sample foods
    for (const food of sampleFoods) {
      await Food.findOneAndUpdate(
        { source: food.source, externalId: food.externalId },
        { $set: food },
        { upsert: true }
      );
      console.log(`Upserted: ${food.name}`);
    }

    console.log(`\nSeeded ${sampleFoods.length} foods successfully!`);
    process.exit(0);
  } catch (error) {
    console.error("Seed error:", error);
    process.exit(1);
  }
}

seed();
