name: DietAppRunner
options:
  bundleIdPrefix: com.dietapp
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"

packages:
  DietApp:
    path: ..

targets:
  DietAppRunner:
    type: application
    platform: iOS
    sources:
      - path: Sources
    resources:
      - path: Sources/Assets.xcassets
    dependencies:
      - package: DietApp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.fuelvio.app
        PRODUCT_NAME: Fuelvio
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: Fuelvio
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_NSCameraUsageDescription: "We need camera access to take photos of your food for logging."
        INFOPLIST_KEY_NSSpeechRecognitionUsageDescription: "We need speech recognition to log food by voice."
        INFOPLIST_KEY_NSMicrophoneUsageDescription: "We need microphone access for voice food logging."
